idf_component_register(
    SRCS
        "main.cpp"
        "WiimService.cpp"
        "models/DeviceStatus.cpp"
        "platform/esp/EspHttpClient.cpp"
        "platform/esp/BoardLed.cpp"
        "platform/esp/Buttons.cpp"
        "platform/esp/RotaryEncoder.cpp"
    INCLUDE_DIRS
        "."
    REQUIRES
        nvs_flash
        esp_event
        esp_netif
        esp_wifi
        esp_http_client
        esp_timer
        driver
)
