using System.Text.Json.Serialization;

namespace WiimController.Models
{
    public class DeviceStatus
    {
        [JsonPropertyName("language")] public string Language { get; set; }
        [JsonPropertyName("ssid")] public string Ssid { get; set; }
        [JsonPropertyName("hideSSID")] public string HideSsid { get; set; }
        [JsonPropertyName("firmware")] public string Firmware { get; set; }
        [JsonPropertyName("build")] public string Build { get; set; }
        [JsonPropertyName("project")] public string Project { get; set; }
        [JsonPropertyName("priv_prj")] public string PrivPrj { get; set; }
        [JsonPropertyName("project_build_name")] public string ProjectBuildName { get; set; }
        [JsonPropertyName("Release")] public string Release { get; set; }
        [JsonPropertyName("FW_Release_version")] public string FwReleaseVersion { get; set; }
        [JsonPropertyName("PCB_version")] public string PcbVersion { get; set; }
        [JsonPropertyName("cast_enable")] public int CastEnable { get; set; }
        [JsonPropertyName("cast_usage_report")] public int CastUsageReport { get; set; }
        [JsonPropertyName("group")] public string Group { get; set; }
        [JsonPropertyName("wmrm_version")] public string WmrmVersion { get; set; }
        [JsonPropertyName("wmrm_sub_ver")] public string WmrmSubVer { get; set; }
        [JsonPropertyName("expired")] public string Expired { get; set; }
        [JsonPropertyName("internet")] public string Internet { get; set; }
        [JsonPropertyName("uuid")] public string Uuid { get; set; }
        [JsonPropertyName("MAC")] public string Mac { get; set; }
        [JsonPropertyName("BTMAC")] public string BtMac { get; set; }
        [JsonPropertyName("InitialConfiguration")] public string InitialConfiguration { get; set; }
        [JsonPropertyName("AP_MAC")] public string ApMac { get; set; }
        [JsonPropertyName("date")] public string Date { get; set; }
        [JsonPropertyName("time")] public string Time { get; set; }
        [JsonPropertyName("netstat")] public string Netstat { get; set; }
        [JsonPropertyName("essid")] public string Essid { get; set; }
        [JsonPropertyName("apcli0")] public string Apcli0 { get; set; }
        [JsonPropertyName("eth0")] public string Eth0 { get; set; }
        [JsonPropertyName("eth2")] public string Eth2 { get; set; }
        [JsonPropertyName("ETH_MAC")] public string EthMac { get; set; }
        [JsonPropertyName("hardware")] public string Hardware { get; set; }
        [JsonPropertyName("ota_api_ver")] public string OtaApiVer { get; set; }
        [JsonPropertyName("VersionUpdate")] public string VersionUpdate { get; set; }
        [JsonPropertyName("NewVer")] public string NewVer { get; set; }
        [JsonPropertyName("mcu_ver")] public string McuVer { get; set; }
        [JsonPropertyName("mcu_ver_new")] public string McuVerNew { get; set; }
        [JsonPropertyName("update_check_count")] public string UpdateCheckCount { get; set; }
        [JsonPropertyName("BleRemote_update_checked_counter")] public string BleRemoteUpdateCheckedCounter { get; set; }
        [JsonPropertyName("ra0")] public string Ra0 { get; set; }
        [JsonPropertyName("temp_uuid")] public string TempUuid { get; set; }
        [JsonPropertyName("cap1")] public string Cap1 { get; set; }
        [JsonPropertyName("capability")] public string Capability { get; set; }
        [JsonPropertyName("languages")] public string Languages { get; set; }
        [JsonPropertyName("prompt_status")] public string PromptStatus { get; set; }
        [JsonPropertyName("alexa_ver")] public string AlexaVer { get; set; }
        [JsonPropertyName("alexa_beta_enable")] public string AlexaBetaEnable { get; set; }
        [JsonPropertyName("alexa_force_beta_cfg")] public string AlexaForceBetaCfg { get; set; }
        [JsonPropertyName("dsp_ver")] public string DspVer { get; set; }
        [JsonPropertyName("ModuleColorNumber")] public string ModuleColorNumber { get; set; }
        [JsonPropertyName("ModuleColorString")] public string ModuleColorString { get; set; }
        [JsonPropertyName("dsp_ver_new")] public string DspVerNew { get; set; }
        [JsonPropertyName("uboot_verinfo")] public string UbootVerinfo { get; set; }
        [JsonPropertyName("kernel_verinfo")] public string KernelVerinfo { get; set; }
        [JsonPropertyName("silence_ota_flag")] public string SilenceOtaFlag { get; set; }
        [JsonPropertyName("ota_interface_ver")] public string OtaInterfaceVer { get; set; }
        [JsonPropertyName("streams_all")] public string StreamsAll { get; set; }
        [JsonPropertyName("streams")] public string Streams { get; set; }
        [JsonPropertyName("region")] public string Region { get; set; }
        [JsonPropertyName("volume_control")] public string VolumeControl { get; set; }
        [JsonPropertyName("external")] public string External { get; set; }
        [JsonPropertyName("preset_key")] public string PresetKey { get; set; }
        [JsonPropertyName("plm_support")] public string PlmSupport { get; set; }
        [JsonPropertyName("mqtt_support")] public string MqttSupport { get; set; }
        [JsonPropertyName("lbc_support")] public string LbcSupport { get; set; }
        [JsonPropertyName("WifiChannel")] public string WifiChannel { get; set; }
        [JsonPropertyName("RSSI")] public string Rssi { get; set; }
        [JsonPropertyName("BSSID")] public string Bssid { get; set; }
        [JsonPropertyName("wlanSnr")] public string WlanSnr { get; set; }
        [JsonPropertyName("wlanNoise")] public string WlanNoise { get; set; }
        [JsonPropertyName("wlanFreq")] public string WlanFreq { get; set; }
        [JsonPropertyName("wlanDataRate")] public string WlanDataRate { get; set; }
        [JsonPropertyName("battery")] public string Battery { get; set; }
        [JsonPropertyName("battery_percent")] public string BatteryPercent { get; set; }
        [JsonPropertyName("securemode")] public string Securemode { get; set; }
        [JsonPropertyName("upnp_version")] public string UpnpVersion { get; set; }
        [JsonPropertyName("upnp_uuid")] public string UpnpUuid { get; set; }
        [JsonPropertyName("uart_pass_port")] public string UartPassPort { get; set; }
        [JsonPropertyName("communication_port")] public string CommunicationPort { get; set; }
        [JsonPropertyName("web_firmware_update_hide")] public string WebFirmwareUpdateHide { get; set; }
        [JsonPropertyName("new_tunein_preset_and_alarm")] public string NewTuneinPresetAndAlarm { get; set; }
        [JsonPropertyName("new_iheart_podcast")] public string NewIheartPodcast { get; set; }
        [JsonPropertyName("tidal_version")] public string TidalVersion { get; set; }
        [JsonPropertyName("service_version")] public string ServiceVersion { get; set; }
        [JsonPropertyName("HiFiSRC_version")] public string HiFiSrcVersion { get; set; }
        [JsonPropertyName("EQ_support")] public string EqSupport { get; set; }
        [JsonPropertyName("EQVersion")] public string EqVersion { get; set; }
        [JsonPropertyName("audio_channel_config")] public string AudioChannelConfig { get; set; }
        [JsonPropertyName("app_timezone_id")] public string AppTimezoneId { get; set; }
        [JsonPropertyName("avs_timezone_id")] public string AvsTimezoneId { get; set; }
        [JsonPropertyName("tz_info_ver")] public string TzInfoVer { get; set; }
        [JsonPropertyName("tz")] public string Tz { get; set; }
        [JsonPropertyName("max_volume")] public string MaxVolume { get; set; }
        [JsonPropertyName("power_mode")] public string PowerMode { get; set; }
        [JsonPropertyName("security")] public string Security { get; set; }
        [JsonPropertyName("security_version")] public string SecurityVersion { get; set; }
        [JsonPropertyName("security_capabilities")] public SecurityCapabilities SecurityCapabilities { get; set; }
        [JsonPropertyName("public_https_version")] public string PublicHttpsVersion { get; set; }
        [JsonPropertyName("BleRemoteControl")] public string BleRemoteControl { get; set; }
        [JsonPropertyName("BleRemoteConnected")] public string BleRemoteConnected { get; set; }
        [JsonPropertyName("BleRemoteException")] public string BleRemoteException { get; set; }
        [JsonPropertyName("autoSenseVersion")] public string AutoSenseVersion { get; set; }
        [JsonPropertyName("set_play_mode_enable")] public string SetPlayModeEnable { get; set; }
        [JsonPropertyName("set_play_mode_gain")] public string SetPlayModeGain { get; set; }
        [JsonPropertyName("privacy_mode")] public string PrivacyMode { get; set; }
        [JsonPropertyName("DeviceName")] public string DeviceName { get; set; }
        [JsonPropertyName("GroupName")] public string GroupName { get; set; }
    }
}
