[env:esp32dev]
platform = espressif32
board = esp32dev
framework = espidf
monitor_speed = 115200
upload_speed = 921600
upload_port = COM3
monitor_port = COM3
lib_deps =
    bblanchon/ArduinoJson@^7.0.4
